name: Telegram News Bot

on:

  workflow_dispatch:

  schedule:

    - cron: "*/20 * * * *"

permissions:
  contents: write

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:

          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run Bot

        env:

          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}

        run: python main.py

      - name: Commit sent.json

        run: |

          git config user.name github-actions

          git config user.email github-actions@github.com

          git add sent.json

          git commit -m "update" || echo "nothing"

          git push
